---

- name: Install packages
  macports:
    name:
      - alacritty
      - helm-3.4
      - terraform-0.12
      - kubectl-1.18
      - aria2
      - awscli
      - go
      - azure-cli
      - bitwarden-cli
      - fzf
      - gawk
      - gpg
      - helm
      - k3d
      - kubectl
      - neovim
      - nnn
      - npm6
      - pipenv
      - ripgrep
      - sops
      - tfenv
      - tmux
      - tree
    update_cache: yes
