- name: Download MacPorts
  get_url:
    url: https://github.com/macports/macports-base/releases/download/v2.7.1/MacPorts-2.7.1-10.15-Catalina.pkg
    dest: /tmp/MacPorts.pkg

- name: Install MacPorts
  become: yes
  command:
    cmd: installer -package /tmp/MacPorts.pkg -target LocalSystem
    creates: /opt/local/bin/port
