---

- name: Get MacPorts source
  git:
    repo: https://github.com/macports/macports-base.git
    dest: ~/.local/src/macport-base
    version: v2.6.4

- name: Config MacPorts
  command: ./configure --prefix={{ ansible_env.HOME }}/.local --with-applications-dir={{ ansible_env.HOME }}/.local/Applications --with-install-user=kdoan --with-install-group=staff --without-startupitems
  args:
    chdir: ~/.local/src/macport-base

- name: Build MacPorts
  make:
    chdir: ~/.local/src/macport-base

- name: Install MacPorts
  make:
    chdir: ~/.local/src/macport-base
    target: install

- name: Clean up
  make:
    chdir: ~/.local/src/macport-base
    target: distclean
