#!/bin/sh

# layout
yabai -m config layout bsp

# gaps
yabai -m config top_padding    15
yabai -m config bottom_padding 15
yabai -m config left_padding   15
yabai -m config right_padding  15
yabai -m config window_gap     15
yabai -m config --space 1 top_padding    0
yabai -m config --space 1 bottom_padding 0
yabai -m config --space 1 left_padding   0
yabai -m config --space 1 right_padding  0
yabai -m config --space 1 window_gap     0

# window opacity
yabai -m config window_opacity on
yabai -m config normal_window_opacity 0.75

# ignore
yabai -m rule --add manage=off app="^System Preferences$"
yabai -m rule --add manage=off app="^Viscosity$"
