#!/bin/sh

# support functions
create_workspaces() {
    current_workspace_count="$(yabai -m query --spaces | jq length)"

    for i in $(seq 1 $(expr "${1}" - "${current_workspace_count}")); do
        yabai -m space --create
    done
}

# load scripting addition
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# ensure a number of workspaces exists
create_workspaces 10

# layout
yabai -m config layout bsp

# gaps
yabai -m config top_padding    15
yabai -m config bottom_padding 15
yabai -m config left_padding   15
yabai -m config right_padding  15
yabai -m config window_gap     15

# window opacity
yabai -m config window_opacity on
yabai -m config normal_window_opacity 0.75

# ignore
yabai -m rule --add manage=off app="^Docker Desktop$"
yabai -m rule --add manage=off app="^System Preferences$"
yabai -m rule --add manage=off app="^Viscosity$"
