- name: Automatically hide and show the dock
  osx_defaults:
    domain: com.apple.dock
    key: autohide
    type: bool
    value: 1
  notify: Reload Dock

- name: Disable automatically rearrange Spaces
  osx_defaults:
    domain: com.apple.dock
    key: mru-spaces
    type: bool
    value: 0
  notify: Reload Dock
